[package]
name = "bevy_ref_component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
crossbeam-channel = "0.5.2"
parking_lot = "0.12.0"
serde = "1.0.127"
